### ISSUE TITLE
Bug in 2 Player mode 

### ISSUE THREAD

**Issue by jean-lucas** [dukebw/Connect_4#6]
I found a bug in the 2 player mode, as you can see in the image red wins when it does not have 4 adjacent red tokens...
Anyone know where this could have come from?

![bugconnect4](https://cloud.githubusercontent.com/assets/8807334/6649774/f637a67a-c9c9-11e4-81af-d561767ac6aa.png)

**Comment by levineza** [comment]
I just tested your same moves and the problem is also in the setup mode; therefore it is likely a problem with the function that checks if the game has been won. I'll checkout an older version of the game if the behaviour is the same then it will be even more likely that is the problem; I'll let you know what I find

**Comment by levineza** [comment]
Yes, the bug is there on the version we handed in for assignment 1; so the
problem is most likely in the function that checks if the board is in a
winning state. The picture below is from the version of the game that we
handed in for assignment 1.
[image: Inline image 1]

**Comment by dukebw** [comment]
I fixed this this morning. It was just a bad out of bounds check in the didColourWin function. I have fixed the exact same issue before, so at some point my fix was reverted back to the buggy state. Be careful when reverting back to old commits (I know I may well have been the person who reverted it, lol) :P
